/**
 * The owner's conversation, and the changes it is waiting on them for.
 *
 * Deliberately its own pair of tables. `message` is a customer talking to a
 * business; this is the owner talking to the thing that runs the businesses,
 * and folding them together would put an owner's instructions into a transcript
 * the assistant reads back to customers.
 */

import { generateId } from "@muxel/core";
import type { Env } from "../env.js";

const now = (): string => new Date().toISOString();

export interface OperatorMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  createdAt: string;
}

export interface OperatorChat {
  id: string;
  title: string;
  model: string;
  updatedAt: string;
}

/**
 * A title taken from the first thing the owner said.
 *
 * Not asked for and not generated by a model: the opening question is what the
 * conversation is about, and spending a call to rephrase it would cost the
 * owner tokens to be told something they just typed.
 */
export function titleFrom(text: string): string {
  const line = text.trim().split("\n")[0] ?? "";
  const cut = line.length > 52 ? `${line.slice(0, 52).trimEnd()}…` : line;
  return cut.length > 0 ? cut : "New chat";
}

export async function listChats(env: Env, userId: number, limit = 40): Promise<OperatorChat[]> {
  const result = await env.DB.prepare(
    "SELECT id, title, model, updated_at FROM operator_chat WHERE user_id = ? ORDER BY updated_at DESC LIMIT ?",
  )
    .bind(userId, limit)
    .all<{ id: string; title: string; model: string; updated_at: string }>();
  return result.results.map((row) => ({
    id: row.id,
    title: row.title,
    model: row.model,
    updatedAt: row.updated_at,
  }));
}

export async function getChat(
  env: Env,
  userId: number,
  chatId: string,
): Promise<OperatorChat | null> {
  const row = await env.DB.prepare(
    "SELECT id, title, model, updated_at FROM operator_chat WHERE id = ? AND user_id = ?",
  )
    .bind(chatId, userId)
    .first<{ id: string; title: string; model: string; updated_at: string }>();
  return row === null
    ? null
    : { id: row.id, title: row.title, model: row.model, updatedAt: row.updated_at };
}

export async function createChat(
  env: Env,
  userId: number,
  title: string,
  model: string,
): Promise<OperatorChat> {
  const id = generateId();
  const stamp = now();
  await env.DB.prepare(
    "INSERT INTO operator_chat (id, user_id, title, model, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
  )
    .bind(id, userId, title, model, stamp, stamp)
    .run();
  return { id, title, model, updatedAt: stamp };
}

export async function setChatModel(
  env: Env,
  userId: number,
  chatId: string,
  model: string,
): Promise<void> {
  await env.DB.prepare("UPDATE operator_chat SET model = ? WHERE id = ? AND user_id = ?")
    .bind(model, chatId, userId)
    .run();
}

export async function deleteChat(env: Env, userId: number, chatId: string): Promise<void> {
  await env.DB.batch([
    env.DB.prepare(
      "DELETE FROM operator_step WHERE message_id IN (SELECT id FROM operator_message WHERE chat_id = ?)",
    ).bind(chatId),
    env.DB.prepare("DELETE FROM operator_message WHERE chat_id = ? AND user_id = ?").bind(
      chatId,
      userId,
    ),
    env.DB.prepare("DELETE FROM operator_chat WHERE id = ? AND user_id = ?").bind(chatId, userId),
    // Anything still waiting refers to a conversation that no longer exists.
    env.DB.prepare(
      `DELETE FROM operator_approval
        WHERE user_id = ? AND state = 'waiting'
          AND message_id IN (SELECT id FROM operator_message WHERE chat_id = ?)`,
    ).bind(userId, chatId),
  ]);
}

export async function chatTranscript(
  env: Env,
  chatId: string,
  limit = 60,
): Promise<OperatorMessage[]> {
  const result = await env.DB.prepare(
    "SELECT id, role, content, created_at FROM operator_message WHERE chat_id = ? ORDER BY created_at DESC LIMIT ?",
  )
    .bind(chatId, limit)
    .all<{ id: string; role: string; content: string; created_at: string }>();
  return result.results
    .map((row) => ({
      id: row.id,
      role: row.role as "user" | "assistant",
      content: row.content,
      createdAt: row.created_at,
    }))
    .reverse();
}

export async function addOperatorMessage(
  env: Env,
  input: { chatId: string; userId: number; role: "user" | "assistant"; content: string },
): Promise<string> {
  const id = generateId();
  const stamp = now();
  await env.DB.batch([
    env.DB.prepare(
      "INSERT INTO operator_message (id, chat_id, user_id, role, content, created_at) VALUES (?, ?, ?, ?, ?, ?)",
    ).bind(id, input.chatId, input.userId, input.role, input.content, stamp),
    // The list is ordered by this, so a chat answered just now sits at the top.
    env.DB.prepare("UPDATE operator_chat SET updated_at = ? WHERE id = ?").bind(stamp, input.chatId),
  ]);
  return id;
}

export interface OperatorStep {
  tool: string;
  ok: boolean;
}

/**
 * Writes down what the assistant looked at, against the answer it produced.
 *
 * Nothing is derived here: the loop reports the tools it actually ran, and this
 * is the only place that record is kept, so the transcript and the live reply
 * show the same list.
 */
export async function recordSteps(
  env: Env,
  messageId: string,
  steps: readonly OperatorStep[],
): Promise<void> {
  if (steps.length === 0) return;
  const stamp = now();
  await env.DB.batch(
    steps.map((step, index) =>
      env.DB.prepare(
        "INSERT INTO operator_step (id, message_id, seq, tool, ok, created_at) VALUES (?, ?, ?, ?, ?, ?)",
      ).bind(generateId(), messageId, index, step.tool, step.ok ? 1 : 0, stamp),
    ),
  );
}

/** The working behind every answer in one chat, keyed by message. */
export async function stepsFor(
  env: Env,
  chatId: string,
): Promise<Record<string, OperatorStep[]>> {
  const result = await env.DB.prepare(
    `SELECT s.message_id, s.tool, s.ok
       FROM operator_step s
       JOIN operator_message m ON m.id = s.message_id
      WHERE m.chat_id = ?
      ORDER BY s.seq`,
  )
    .bind(chatId)
    .all<{ message_id: string; tool: string; ok: number }>();
  const byMessage: Record<string, OperatorStep[]> = {};
  for (const row of result.results) {
    (byMessage[row.message_id] ??= []).push({ tool: row.tool, ok: row.ok === 1 });
  }
  return byMessage;
}

export interface Approval {
  id: string;
  messageId: string;
  tool: string;
  args: Record<string, unknown>;
  summary: string;
  state: "waiting" | "approved" | "declined" | "failed";
  result: string;
  createdAt: string;
}

function toApproval(row: {
  id: string;
  message_id: string;
  tool: string;
  args: string;
  summary: string;
  state: string;
  result: string;
  created_at: string;
}): Approval {
  let args: Record<string, unknown> = {};
  try {
    args = JSON.parse(row.args) as Record<string, unknown>;
  } catch {
    // A damaged row still shows what it was for; running it is refused below.
  }
  return {
    id: row.id,
    messageId: row.message_id,
    tool: row.tool,
    args,
    summary: row.summary,
    state: row.state as Approval["state"],
    result: row.result,
    createdAt: row.created_at,
  };
}

export async function askApproval(
  env: Env,
  input: {
    userId: number;
    messageId: string;
    tool: string;
    args: Record<string, unknown>;
    summary: string;
  },
): Promise<Approval> {
  const id = generateId();
  const stamp = now();
  await env.DB.prepare(
    `INSERT INTO operator_approval (id, user_id, message_id, tool, args, summary, state, result, created_at)
     VALUES (?, ?, ?, ?, ?, ?, 'waiting', '', ?)`,
  )
    .bind(id, input.userId, input.messageId, input.tool, JSON.stringify(input.args), input.summary, stamp)
    .run();
  return {
    id,
    messageId: input.messageId,
    tool: input.tool,
    args: input.args,
    summary: input.summary,
    state: "waiting",
    result: "",
    createdAt: stamp,
  };
}

export async function listApprovals(env: Env, userId: number, limit = 40): Promise<Approval[]> {
  const result = await env.DB.prepare(
    "SELECT * FROM operator_approval WHERE user_id = ? ORDER BY created_at DESC LIMIT ?",
  )
    .bind(userId, limit)
    .all<Parameters<typeof toApproval>[0]>();
  return result.results.map(toApproval).reverse();
}

export async function getApproval(
  env: Env,
  userId: number,
  approvalId: string,
): Promise<Approval | null> {
  const row = await env.DB.prepare(
    "SELECT * FROM operator_approval WHERE id = ? AND user_id = ?",
  )
    .bind(approvalId, userId)
    .first<Parameters<typeof toApproval>[0]>();
  return row === null ? null : toApproval(row);
}

/**
 * Records what happened to a pending change.
 *
 * Only a row that is still waiting can move. A second yes on the same card must
 * not run the same write twice, and the state column is what makes that a fact
 * rather than a race the console has to avoid.
 */
export async function settleApproval(
  env: Env,
  userId: number,
  approvalId: string,
  state: "approved" | "declined" | "failed",
  result: string,
): Promise<boolean> {
  const outcome = await env.DB.prepare(
    "UPDATE operator_approval SET state = ?, result = ?, decided_at = ? WHERE id = ? AND user_id = ? AND state = 'waiting'",
  )
    .bind(state, result.slice(0, 2000), now(), approvalId, userId)
    .run();
  return (outcome.meta?.changes ?? 0) > 0;
}
