/**
 * The owner's conversation, and the changes it is waiting on them for.
 *
 * Deliberately its own pair of tables. `message` is a customer talking to a
 * business; this is the owner talking to the thing that runs the businesses,
 * and folding them together would put an owner's instructions into a transcript
 * the assistant reads back to customers.
 */

import { generateId } from "@muxel/core";
import type { Env } from "../env.js";

const now = (): string => new Date().toISOString();

export interface OperatorMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  createdAt: string;
}

export interface OperatorChat {
  id: string;
  title: string;
  model: string;
  updatedAt: string;
}

/**
 * A title taken from the first thing the owner said.
 *
 * Not asked for and not generated by a model: the opening question is what the
 * conversation is about, and spending a call to rephrase it would cost the
 * owner tokens to be told something they just typed.
 */
export function titleFrom(text: string): string {
  const line = text.trim().split("\n")[0] ?? "";
  const cut = line.length > 52 ? `${line.slice(0, 52).trimEnd()}…` : line;
  return cut.length > 0 ? cut : "New chat";
}

export async function listChats(env: Env, userId: number, limit = 40): Promise<OperatorChat[]> {
  const result = await env.DB.prepare(
    "SELECT id, title, model, updated_at FROM operator_chat WHERE user_id = ? ORDER BY updated_at DESC LIMIT ?",
  )
    .bind(userId, limit)
    .all<{ id: string; title: string; model: string; updated_at: string }>();
  return result.results.map((row) => ({
    id: row.id,
    title: row.title,
    model: row.model,
    updatedAt: row.updated_at,
  }));
}

export async function getChat(
  env: Env,
  userId: number,
  chatId: string,
): Promise<OperatorChat | null> {
  const row = await env.DB.prepare(
    "SELECT id, title, model, updated_at FROM operator_chat WHERE id = ? AND user_id = ?",
  )
    .bind(chatId, userId)
    .first<{ id: string; title: string; model: string; updated_at: string }>();
  return row === null
    ? null
    : { id: row.id, title: row.title, model: row.model, updatedAt: row.updated_at };
}

export async function createChat(
  env: Env,
  userId: number,
  title: string,
  model: string,
): Promise<OperatorChat> {
  const id = generateId();
  const stamp = now();
  await env.DB.prepare(
    "INSERT INTO operator_chat (id, user_id, title, model, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
  )
    .bind(id, userId, title, model, stamp, stamp)
    .run();
  return { id, title, model, updatedAt: stamp };
}

export async function setChatModel(
  env: Env,
  userId: number,
  chatId: string,
  model: string,
): Promise<void> {
  await env.DB.prepare("UPDATE operator_chat SET model = ? WHERE id = ? AND user_id = ?")
    .bind(model, chatId, userId)
    .run();
}

export async function deleteChat(env: Env, userId: number, chatId: string): Promise<void> {
  await env.DB.batch([
    env.DB.prepare(
      "DELETE FROM operator_step WHERE message_id IN (SELECT id FROM operator_message WHERE chat_id = ?)",
    ).bind(chatId),
    env.DB.prepare(
      "DELETE FROM operator_usage WHERE message_id IN (SELECT id FROM operator_message WHERE chat_id = ?)",
    ).bind(chatId),
    env.DB.prepare(
      "DELETE FROM operator_prompt WHERE message_id IN (SELECT id FROM operator_message WHERE chat_id = ?)",
    ).bind(chatId),
    env.DB.prepare("DELETE FROM operator_message WHERE chat_id = ? AND user_id = ?").bind(
      chatId,
      userId,
    ),
    env.DB.prepare("DELETE FROM operator_chat WHERE id = ? AND user_id = ?").bind(chatId, userId),
    // Anything still waiting refers to a conversation that no longer exists.
    env.DB.prepare(
      `DELETE FROM operator_approval
        WHERE user_id = ? AND state = 'waiting'
          AND message_id IN (SELECT id FROM operator_message WHERE chat_id = ?)`,
    ).bind(userId, chatId),
  ]);
}

export async function chatTranscript(
  env: Env,
  chatId: string,
  limit = 60,
): Promise<OperatorMessage[]> {
  const result = await env.DB.prepare(
    "SELECT id, role, content, created_at FROM operator_message WHERE chat_id = ? ORDER BY created_at DESC LIMIT ?",
  )
    .bind(chatId, limit)
    .all<{ id: string; role: string; content: string; created_at: string }>();
  return result.results
    .map((row) => ({
      id: row.id,
      role: row.role as "user" | "assistant",
      content: row.content,
      createdAt: row.created_at,
    }))
    .reverse();
}

export async function addOperatorMessage(
  env: Env,
  input: { chatId: string; userId: number; role: "user" | "assistant"; content: string },
): Promise<string> {
  const id = generateId();
  const stamp = now();
  await env.DB.batch([
    env.DB.prepare(
      "INSERT INTO operator_message (id, chat_id, user_id, role, content, created_at) VALUES (?, ?, ?, ?, ?, ?)",
    ).bind(id, input.chatId, input.userId, input.role, input.content, stamp),
    // The list is ordered by this, so a chat answered just now sits at the top.
    env.DB.prepare("UPDATE operator_chat SET updated_at = ? WHERE id = ?").bind(stamp, input.chatId),
  ]);
  return id;
}

export interface OperatorStep {
  tool: string;
  ok: boolean;
}

/**
 * Writes down what the assistant looked at, against the answer it produced.
 *
 * Nothing is derived here: the loop reports the tools it actually ran, and this
 * is the only place that record is kept, so the transcript and the live reply
 * show the same list.
 */
export async function recordSteps(
  env: Env,
  messageId: string,
  steps: readonly OperatorStep[],
): Promise<void> {
  if (steps.length === 0) return;
  const stamp = now();
  await env.DB.batch(
    steps.map((step, index) =>
      env.DB.prepare(
        "INSERT INTO operator_step (id, message_id, seq, tool, ok, created_at) VALUES (?, ?, ?, ?, ?, ?)",
      ).bind(generateId(), messageId, index, step.tool, step.ok ? 1 : 0, stamp),
    ),
  );
}

/** The working behind every answer in one chat, keyed by message. */
export async function stepsFor(
  env: Env,
  chatId: string,
): Promise<Record<string, OperatorStep[]>> {
  const result = await env.DB.prepare(
    `SELECT s.message_id, s.tool, s.ok
       FROM operator_step s
       JOIN operator_message m ON m.id = s.message_id
      WHERE m.chat_id = ?
      ORDER BY s.seq`,
  )
    .bind(chatId)
    .all<{ message_id: string; tool: string; ok: number }>();
  const byMessage: Record<string, OperatorStep[]> = {};
  for (const row of result.results) {
    (byMessage[row.message_id] ??= []).push({ tool: row.tool, ok: row.ok === 1 });
  }
  return byMessage;
}

export interface MessageUsage {
  model: string;
  inputTokens: number;
  outputTokens: number;
}

/** What one answer cost, against the answer itself. */
export async function recordUsageFor(
  env: Env,
  messageId: string,
  usage: MessageUsage,
): Promise<void> {
  await env.DB.prepare(
    `INSERT OR REPLACE INTO operator_usage
       (message_id, model, input_tokens, output_tokens, created_at)
     VALUES (?, ?, ?, ?, ?)`,
  )
    .bind(messageId, usage.model, usage.inputTokens, usage.outputTokens, now())
    .run();
}

/** Every answer's cost in one chat, keyed by message. */
export async function usageFor(
  env: Env,
  chatId: string,
): Promise<Record<string, MessageUsage>> {
  const result = await env.DB.prepare(
    `SELECT u.message_id, u.model, u.input_tokens, u.output_tokens
       FROM operator_usage u
       JOIN operator_message m ON m.id = u.message_id
      WHERE m.chat_id = ?`,
  )
    .bind(chatId)
    .all<{ message_id: string; model: string; input_tokens: number; output_tokens: number }>();
  const byMessage: Record<string, MessageUsage> = {};
  for (const row of result.results) {
    byMessage[row.message_id] = {
      model: row.model,
      inputTokens: row.input_tokens,
      outputTokens: row.output_tokens,
    };
  }
  return byMessage;
}

/** What a turn is waiting on the owner for, kept against the turn. */
export async function recordPrompt(
  env: Env,
  messageId: string,
  prompt: { kind: string } & Record<string, unknown>,
): Promise<void> {
  await env.DB.prepare(
    "INSERT OR REPLACE INTO operator_prompt (message_id, kind, payload, created_at) VALUES (?, ?, ?, ?)",
  )
    .bind(messageId, prompt.kind, JSON.stringify(prompt), now())
    .run();
}

/** Every open question in one chat, keyed by the message that asked it. */
export async function promptsFor(
  env: Env,
  chatId: string,
): Promise<Record<string, Record<string, unknown>>> {
  const result = await env.DB.prepare(
    `SELECT p.message_id, p.payload
       FROM operator_prompt p
       JOIN operator_message m ON m.id = p.message_id
      WHERE m.chat_id = ?`,
  )
    .bind(chatId)
    .all<{ message_id: string; payload: string }>();
  const byMessage: Record<string, Record<string, unknown>> = {};
  for (const row of result.results) {
    try {
      byMessage[row.message_id] = JSON.parse(row.payload) as Record<string, unknown>;
    } catch {
      // A damaged row is a question that cannot be offered. The text of the
      // answer still carries it, so the owner can still reply by typing.
    }
  }
  return byMessage;
}

export interface Approval {
  id: string;
  messageId: string;
  tool: string;
  args: Record<string, unknown>;
  summary: string;
  state: "waiting" | "approved" | "declined" | "failed";
  result: string;
  createdAt: string;
}

function toApproval(row: {
  id: string;
  message_id: string;
  tool: string;
  args: string;
  summary: string;
  state: string;
  result: string;
  created_at: string;
}): Approval {
  let args: Record<string, unknown> = {};
  try {
    args = JSON.parse(row.args) as Record<string, unknown>;
  } catch {
    // A damaged row still shows what it was for; running it is refused below.
  }
  return {
    id: row.id,
    messageId: row.message_id,
    tool: row.tool,
    args,
    summary: row.summary,
    state: row.state as Approval["state"],
    result: row.result,
    createdAt: row.created_at,
  };
}

/**
 * Records a change the owner has to decide, before the answer proposing it
 * exists.
 *
 * Raised with no message, because at this moment there is no message it belongs
 * to: the loop is still working and the turn's answer is written at the end.
 * `attachApprovals` files it against that answer — the message the owner reads,
 * and the message the card is drawn under.
 *
 * It used to be filed against the owner's own question, the only id that
 * existed at this point. The console draws cards on answers, so every card was
 * discarded, and the owner was told 25 changes were waiting with nothing on
 * screen to tap.
 */
export async function askApproval(
  env: Env,
  input: {
    userId: number;
    tool: string;
    args: Record<string, unknown>;
    summary: string;
  },
): Promise<Approval> {
  const id = generateId();
  const stamp = now();
  const messageId = "";
  await env.DB.prepare(
    `INSERT INTO operator_approval (id, user_id, message_id, tool, args, summary, state, result, created_at)
     VALUES (?, ?, ?, ?, ?, ?, 'waiting', '', ?)`,
  )
    .bind(id, input.userId, messageId, input.tool, JSON.stringify(input.args), input.summary, stamp)
    .run();
  return {
    id,
    messageId,
    tool: input.tool,
    args: input.args,
    summary: input.summary,
    state: "waiting",
    result: "",
    createdAt: stamp,
  };
}

export async function listApprovals(env: Env, userId: number, limit = 40): Promise<Approval[]> {
  const result = await env.DB.prepare(
    // Only the ones filed against an answer. A change raised by a turn that
    // then failed before it could say anything is one the owner was never
    // shown, and counting it promises a card that was never drawn.
    "SELECT * FROM operator_approval WHERE user_id = ? AND message_id <> '' ORDER BY created_at DESC LIMIT ?",
  )
    .bind(userId, limit)
    .all<Parameters<typeof toApproval>[0]>();
  return result.results.map(toApproval).reverse();
}

/**
 * Files this turn's changes against the answer that proposed them.
 *
 * Done in the same breath as writing that answer, because an approval with no
 * message is one the owner has not been shown and therefore cannot decide.
 */
export async function attachApprovals(
  env: Env,
  approvalIds: readonly string[],
  messageId: string,
): Promise<void> {
  if (approvalIds.length === 0) return;
  await env.DB.batch(
    approvalIds.map((id) =>
      env.DB.prepare("UPDATE operator_approval SET message_id = ? WHERE id = ?").bind(messageId, id),
    ),
  );
}

/**
 * Every change a chat proposed, against the turn that proposed it.
 *
 * The transcript holds what the assistant said, and the approval rows hold what
 * became of what it asked for. Handing back only the first left the model
 * proposing the same change again the moment the owner replied to it, because
 * as far as it could see it had never asked.
 */
export async function approvalsByMessage(
  env: Env,
  chatId: string,
): Promise<Record<string, Approval[]>> {
  const result = await env.DB.prepare(
    `SELECT a.* FROM operator_approval a
       JOIN operator_message m ON m.id = a.message_id
      WHERE m.chat_id = ?
      ORDER BY a.created_at`,
  )
    .bind(chatId)
    .all<Parameters<typeof toApproval>[0]>();
  const byMessage: Record<string, Approval[]> = {};
  for (const row of result.results) {
    const approval = toApproval(row);
    (byMessage[approval.messageId] ??= []).push(approval);
  }
  return byMessage;
}

export async function getApproval(
  env: Env,
  userId: number,
  approvalId: string,
): Promise<Approval | null> {
  const row = await env.DB.prepare(
    "SELECT * FROM operator_approval WHERE id = ? AND user_id = ?",
  )
    .bind(approvalId, userId)
    .first<Parameters<typeof toApproval>[0]>();
  return row === null ? null : toApproval(row);
}

/**
 * Records what happened to a pending change.
 *
 * Only a row that is still waiting can move. A second yes on the same card must
 * not run the same write twice, and the state column is what makes that a fact
 * rather than a race the console has to avoid.
 */
export async function settleApproval(
  env: Env,
  userId: number,
  approvalId: string,
  state: "approved" | "declined" | "failed",
  result: string,
): Promise<boolean> {
  const outcome = await env.DB.prepare(
    "UPDATE operator_approval SET state = ?, result = ?, decided_at = ? WHERE id = ? AND user_id = ? AND state = 'waiting'",
  )
    .bind(state, result.slice(0, 2000), now(), approvalId, userId)
    .run();
  return (outcome.meta?.changes ?? 0) > 0;
}
